// <auto-generated />
using System;
using Blog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Blog.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20200822143514_Biografia")]
    partial class Biografia
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Blog.Models.Biografia", b =>
                {
                    b.Property<int>("BiografiaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Texto");

                    b.HasKey("BiografiaId");

                    b.ToTable("Biografias");
                });

            modelBuilder.Entity("Blog.Models.Materia", b =>
                {
                    b.Property<long?>("MateriaID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Autor");

                    b.Property<DateTime?>("DtCreated");

                    b.Property<byte[]>("Foto");

                    b.Property<string>("FotoMimeType");

                    b.Property<string>("Resumo");

                    b.Property<string>("Texto");

                    b.Property<string>("Titulo");

                    b.HasKey("MateriaID");

                    b.ToTable("Materias");
                });
#pragma warning restore 612, 618
        }
    }
}
